"""Shared machine-readable contracts for pipeline validation outcomes."""

STAGE_EXTRACTION = "extraction"
STAGE_PARSING = "parsing"
STAGE_COMPILATION = "compilation"
STAGE_EXECUTION = "execution"
STAGE_DISCOVERY = "discovery"
STAGE_INSTANTIATION = "instantiation"
STAGE_VIEW_ACCESS = "view_access"
STAGE_RENDERING = "rendering"
STAGE_SPACING = "spacing"
STAGE_RUNTIME = "validation_runtime"

ERR_NONE = ""
ERR_NO_ORD_CODE = "no_ord_code_extracted"
ERR_PARSE_FAILURE = "parse_failure"
ERR_COMPILE_FAILURE = "compile_failure"
ERR_EXEC_FAILURE = "exec_failure"
ERR_NO_CELL_DISCOVERED = "no_cell_discovered"
ERR_MISSING_REQUIRED_PARAMS = "missing_required_params"
ERR_INSTANTIATION_FAILURE = "instantiation_failure"
ERR_VIEW_ACCESS_FAILURE = "view_access_failure"
ERR_RENDER_FAILURE = "render_failure"
ERR_SPACING_VIOLATION = "spacing_violation"
ERR_VALIDATION_RUNTIME = "validation_runtime_failure"
